# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afbeeadf56b64b764382cbbe95d8263aa521ff7145ea073f782cd60a0560e06fd07b1f19a8811924450d288e830bcb9e349ec4f7205ba37f7aa214189452582a

test:
  secret_key_base: 1660307593e940725ac7101acc8bcc64ecb5088838f2aa3599bb2cf06149602e0ea38f5ec6c5a3aaa9c983fb044270d3542333e2b60a731756a37a8f9bc02475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
